import Slider from "../../components/Slider/Slider";
import Image from 'react-bootstrap/Image'
import "./Home.css"

const Home = () => {
    return ( 
        <div className="home">
            <Slider />
            <div>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ornare laoreet massa nec sollicitudin. Donec quis faucibus tortor. Aliquam tempor dolor ut mi faucibus cursus. Pellentesque nec augue at ante congue consequat eu luctus elit. Cras a sem vestibulum, dictum tortor quis, viverra ante. Fusce aliquet dui feugiat orci posuere interdum. Aenean leo augue, facilisis sit amet tempor at, feugiat non nibh. Nullam est sem, mattis id orci et, mattis porta augue.</p>
                <p>Vivamus quis eleifend lectus, quis efficitur nunc. Duis congue massa a risus mollis convallis. Ut eu risus vehicula, aliquam nisi non, pretium nisl. Donec non velit vulputate, elementum felis eu, pharetra lectus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque rutrum ultricies est, et facilisis lorem pulvinar in. Aenean id dictum dui. In hac habitasse platea dictumst. Aliquam finibus turpis vitae imperdiet viverra. Sed lacus risus, gravida pretium lorem vel, interdum gravida eros. Sed vitae blandit libero. Curabitur posuere metus risus, vel venenatis nisl egestas sed. Vivamus in viverra sem. Nullam malesuada sapien est, at mattis nisi venenatis quis. Etiam turpis nisi, vulputate et dui vitae, placerat fringilla metus.</p>
                <Image src={`${process.env.PUBLIC_URL}/assets/images/sliders/slide-one.png`} rounded={true} width="100%"/>
                <p>Phasellus nec nibh enim. Mauris id erat aliquet, posuere ex ut, scelerisque augue. Nunc pharetra, ligula id congue hendrerit, augue nisi aliquet sem, euismod interdum quam nisi a diam. Pellentesque consequat odio sed pharetra placerat. Phasellus metus mauris, semper in accumsan a, condimentum quis diam. Ut ultricies gravida est ut tincidunt. Integer pretium, massa non varius tincidunt, nibh enim malesuada justo, nec condimentum ex urna sit amet tellus. Cras eget mattis diam. Nunc nec dictum elit. Maecenas egestas vulputate magna, in ultricies orci convallis id. Phasellus quam felis, elementum ac nunc quis, tincidunt accumsan ligula. Aliquam erat volutpat. Integer dictum dui lacus, non facilisis sapien pulvinar quis. Proin lobortis vitae sapien sit amet malesuada. Donec magna sapien, euismod non fringilla vitae, placerat quis ante. Aenean vitae est iaculis ex convallis ornare.</p>
                <p>Phasellus nec nibh enim. Mauris id erat aliquet, posuere ex ut, scelerisque augue. Nunc pharetra, ligula id congue hendrerit, augue nisi aliquet sem, euismod interdum quam nisi a diam. Pellentesque consequat odio sed pharetra placerat. Phasellus metus mauris, semper in accumsan a, condimentum quis diam. Ut ultricies gravida est ut tincidunt. Integer pretium, massa non varius tincidunt, nibh enim malesuada justo, nec condimentum ex urna sit amet tellus. Cras eget mattis diam. Nunc nec dictum elit. Maecenas egestas vulputate magna, in ultricies orci convallis id. Phasellus quam felis, elementum ac nunc quis, tincidunt accumsan ligula. Aliquam erat volutpat. Integer dictum dui lacus, non facilisis sapien pulvinar quis. Proin lobortis vitae sapien sit amet malesuada. Donec magna sapien, euismod non fringilla vitae, placerat quis ante. Aenean vitae est iaculis ex convallis ornare.</p>
                <p>Phasellus nec nibh enim. Mauris id erat aliquet, posuere ex ut, scelerisque augue. Nunc pharetra, ligula id congue hendrerit, augue nisi aliquet sem, euismod interdum quam nisi a diam. Pellentesque consequat odio sed pharetra placerat. Phasellus metus mauris, semper in accumsan a, condimentum quis diam. Ut ultricies gravida est ut tincidunt. Integer pretium, massa non varius tincidunt, nibh enim malesuada justo, nec condimentum ex urna sit amet tellus. Cras eget mattis diam. Nunc nec dictum elit. Maecenas egestas vulputate magna, in ultricies orci convallis id. Phasellus quam felis, elementum ac nunc quis, tincidunt accumsan ligula. Aliquam erat volutpat. Integer dictum dui lacus, non facilisis sapien pulvinar quis. Proin lobortis vitae sapien sit amet malesuada. Donec magna sapien, euismod non fringilla vitae, placerat quis ante. Aenean vitae est iaculis ex convallis ornare.</p>
                <p>Phasellus nec nibh enim. Mauris id erat aliquet, posuere ex ut, scelerisque augue. Nunc pharetra, ligula id congue hendrerit, augue nisi aliquet sem, euismod interdum quam nisi a diam. Pellentesque consequat odio sed pharetra placerat. Phasellus metus mauris, semper in accumsan a, condimentum quis diam. Ut ultricies gravida est ut tincidunt. Integer pretium, massa non varius tincidunt, nibh enim malesuada justo, nec condimentum ex urna sit amet tellus. Cras eget mattis diam. Nunc nec dictum elit. Maecenas egestas vulputate magna, in ultricies orci convallis id. Phasellus quam felis, elementum ac nunc quis, tincidunt accumsan ligula. Aliquam erat volutpat. Integer dictum dui lacus, non facilisis sapien pulvinar quis. Proin lobortis vitae sapien sit amet malesuada. Donec magna sapien, euismod non fringilla vitae, placerat quis ante. Aenean vitae est iaculis ex convallis ornare.</p>                
                <p>Phasellus nec nibh enim. Mauris id erat aliquet, posuere ex ut, scelerisque augue. Nunc pharetra, ligula id congue hendrerit, augue nisi aliquet sem, euismod interdum quam nisi a diam. Pellentesque consequat odio sed pharetra placerat. Phasellus metus mauris, semper in accumsan a, condimentum quis diam. Ut ultricies gravida est ut tincidunt. Integer pretium, massa non varius tincidunt, nibh enim malesuada justo, nec condimentum ex urna sit amet tellus. Cras eget mattis diam. Nunc nec dictum elit. Maecenas egestas vulputate magna, in ultricies orci convallis id. Phasellus quam felis, elementum ac nunc quis, tincidunt accumsan ligula. Aliquam erat volutpat. Integer dictum dui lacus, non facilisis sapien pulvinar quis. Proin lobortis vitae sapien sit amet malesuada. Donec magna sapien, euismod non fringilla vitae, placerat quis ante. Aenean vitae est iaculis ex convallis ornare.</p>
            </div>
        </div>
    );
}
export default Home;